version: 2

project_name: skills-pkg

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: "386"
    main: .
    binary: skills-pkg
    ldflags:
      - -s
      - -w
      - -X 'main.version={{.Version}}'
      - -X 'main.commit={{.Commit}}'
      - -X 'main.date={{.Date}}'

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
nfpms:
  - id: skills-pkg-nfpm
    file_name_template: "{{ .ProjectName }}_{{ .Arch }}"
    homepage: https://github.com/mazrean/skills-pkg
    maintainer: Shunsuke Wakamatsu <50093633+mazrean@users.noreply.github.com>
    description: A CLI tool for managing agent skills
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    mtime: "{{ .CommitDate }}"

# Modern Homebrew configuration (recommended)
brews:
  - repository:
      owner: mazrean
      name: homebrew-tap
    homepage: https://github.com/mazrean/skills-pkg
    description: Agent Skills package manager for Claude Code and Codex CLI
    license: MIT
    commit_author:
      name: Shunsuke Wakamatsu
      email: 50093633+mazrean@users.noreply.github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
